Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  NODES = {
    "maestro" => "192.168.56.10",
    "esclavo1" => "192.168.56.11",
    "esclavo2" => "192.168.56.12",
    "esclavo3" => "192.168.56.13"
  }

  NODES.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip
      node.vm.provider "virtualbox" do |vb|
        vb.name = name
        vb.memory = 1024
        vb.cpus = 1
      end

      node.vm.provision "shell", inline: <<-SHELL
        echo "==> Instalando Docker en #{name}..."
        apt-get update
        apt-get install -y docker.io docker-compose git
        usermod -aG docker vagrant
        
        # Copiar archivos del proyecto
        cp -r /vagrant/* /home/vagrant/hpc/ 2>/dev/null || mkdir -p /home/vagrant/hpc
        chown -R vagrant:vagrant /home/vagrant/hpc
        
        echo "==> #{name} configurado y listo"
      SHELL
    end
  end
end
